# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.parallel=true

# Project
mod_id=nirvana
mod_name=Nirvana
mod_author=possible_triangle
mod_version=0.0.3+1.21.10
maven_group=dev.galena
archives_base_name=nirvana

# Minecraft/Fabric
minecraft_version=1.21.10
yarn_mappings=1.21.10+build.3
loader_version=0.19.3
fabric_version=0.138.4+1.21.10

# Polymer
polymer_version=0.14.4+1.21.10
factorytools_version=0.8.2+1.21.10

# Publishing
repository=teamgalena/nirvana
curseforge_project_id=1278909
modrinth_project_id=7vLeZs9H
