# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

# Project
mod_id=nirvana
mod_name=Nirvana
mod_author=possible_triangle
mod_version=0.0.0-dev
release_type=release

# Common
mc_version=1.21.10
parchment_mappings_version=2025.10.12

# Fabric
fabric_api_version=0.138.3+1.21.10
fabric_loader_version=0.19.3

# Publishing
repository=teamgalena/nirvana
maven_group=dev.galena
curseforge_project_id=1278909
modrinth_project_id=7vLeZs9H
