# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.parallel=true

# Project
mod_id=nirvana
mod_name=Nirvana
mod_author=possible_triangle
mod_version=0.0.5+26.2
maven_group=dev.galena
archives_base_name=nirvana

# Minecraft/Fabric
minecraft_version=26.2
loader_version=0.19.3
fabric_version=0.156.0+26.2

# Polymer
polymer_version=0.17.3+26.2
factorytools_version=0.11.2+26.2

# Publishing
#repository=teamgalena/nirvana
#curseforge_project_id=1278909
#modrinth_project_id=7vLeZs9H
