[versions]
jei = "19.27.0.343"
multikulti = "1.21.1-2.0.2"
config-api-port = "21.10.1"

[libraries]

registrate-neoforge = { module = "com.tterrag.registrate:Registrate", version = "MC1.21.1-1.4.8" }
registrate-fabric = { module = "com.tterrag.registrate_fabric:Registrate", version = "1.3.6-MC1.21.1" }

multikulti-core-common = { group = "com.possible-triangle", name = "multikulti-core-common", version.ref = "multikulti" }
multikulti-registrate-common = { group = "com.possible-triangle", name = "multikulti-registrate-common", version.ref = "multikulti" }
multikulti-core-fabric = { group = "com.possible-triangle", name = "multikulti-core-fabric", version.ref = "multikulti" }
multikulti-registrate-fabric = { group = "com.possible-triangle", name = "multikulti-registrate-fabric", version.ref = "multikulti" }

jei-common-api = { group = "mezz.jei", name = "jei-1.21.1-common-api", version.ref = "jei" }
jei-fabric-api = { group = "mezz.jei", name = "jei-1.21.1-fabric-api", version.ref = "jei" }
jei-fabric = { group = "mezz.jei", name = "jei-1.21.1-fabric", version.ref = "jei" }
jei-lib = { group = "mezz.jei", name = "jei-1.21.1-lib", version.ref = "jei" }

create-fabric = { group = "com.simibubi.create", name = "create-fabric-1.21.1", version = "0.5.1-f-build.1335+mc1.20.1" }

dye-depot-fabric = { group = "com.ninni.dye_depot", name = "dye_depot-fabric", version = "1.21.1-2.1.0" }

config-api-port-fabric = { module = "fuzs.forgeconfigapiport:forgeconfigapiport-fabric", version.ref = "config-api-port" }
config-api-port-common = { module = "fuzs.forgeconfigapiport:forgeconfigapiport-common-neoforgeapi", version.ref = "config-api-port" }

oreganized = { module = "dev.galena:oreganized", version = "5.1.2" }
